extends Control


# Declare member variables here. Examples:
# var a = 2
# var b = "text"
export var player_number :int = 1

onready var health_bar = $"%HealthBar"
onready var stamina_bar = $"%StaminaBar"
onready var selected_inventory_items = $"%SelectedInventoryItems"


# Called when the node enters the scene tree for the first time.
func _ready():
	health_bar.set_player_number(player_number)
	stamina_bar.set_player_number(player_number)
	selected_inventory_items.set_player_number(player_number)

# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	if PlayerInfo.get_player_data(player_number - 1) == null:
		visible = false
